using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;


namespace CookieMod
{
    public static class RecipeHelper
    {
        public static void AddRecipes(Mod mod)
        {
            ModRecipe recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HardCookie");
            recipe.AddTile(TileID.Sinks);
            recipe.SetResult(null, "SoftCookie");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HardCookie");
            recipe.SetResult(null, "CookieCrumbs");
            recipe.AddTile(TileID.Anvils);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "SoftCookie");
            recipe.SetResult(null, "CookieDust", 3);
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SpellTome);
            recipe.AddIngredient(null, "SoftCookie", 15);
            recipe.AddIngredient(null, "CookieDust", 30);
            recipe.SetResult(null, "ChocolateBlast");
            recipe.AddTile(TileID.Bookcases);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "SugarCube");
            recipe.SetResult(null, "SugarDust", 5);
            recipe.AddTile(TileID.Sawmill);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "SugarDust", 5);
            recipe.SetResult(null, "HardSugarDust", 5);
            recipe.AddTile(TileID.Hellforge);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "SugarCube", 30);
            recipe.AddIngredient(null, "CookieCrumbs", 5);
            recipe.SetResult(null, "SugarBlaster");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "SugarDust", 20);
            recipe.AddIngredient(ItemID.Snowball, 15);
            recipe.SetResult(null, "SoftSugarball", 15);
            recipe.AddTile(TileID.WorkBenches);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "HardSugarDust", 20);
            recipe.AddIngredient(ItemID.Snowball, 15);
            recipe.SetResult(null, "HardSugarball", 15);
            recipe.AddTile(TileID.WorkBenches);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.Bottle);
            recipe.SetResult(null, "MilkBottle");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.Bottle);
            recipe.SetResult(ItemID.BottledHoney);
            recipe.AddTile(TileID.HoneyDispenser);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.BottledHoney);
            recipe.AddIngredient(null, "SugarDust", 3);
            recipe.SetResult(null, "SugarHoney");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.BottledWater);
            recipe.AddIngredient(null, "SugarDust", 3);
            recipe.SetResult(null, "SugarWater");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.Silk, 15);
            recipe.AddIngredient(null, "SoftCookie", 20);
            recipe.SetResult(null, "CookieGlove");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "MilkBottle");
            recipe.AddIngredient(null, "SugarDust", 3);
            recipe.AddIngredient(null, "CookieDust", 15);
            recipe.SetResult(null, "ChocolateBottle");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.DirtBlock);
            recipe.AddIngredient(null, "SugarDust", 3);
            recipe.AddIngredient(null, "CookieCrumbs", 5);
            recipe.SetResult(null, "ChocoDirt");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.IronBar, 9);
            recipe.AddIngredient(ItemID.EmptyBucket, 3);
            recipe.SetResult(null, "MilkTank");
            recipe.AddTile(TileID.Anvils);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.WandofSparking);
            recipe.AddIngredient(null, "SugarCube", 20);
            recipe.SetResult(null, "SugarTwig");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.Bottle);
            recipe.SetResult(ItemID.BottledHoney);
            recipe.AddTile(TileID.Hive);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "SugarCube", 10);
            recipe.AddIngredient(null, "SugarDust", 15);
            recipe.SetResult(null, "SpeedBand");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "SugarCube", 5);
            recipe.AddIngredient(null, "SugarDust", 10);
            recipe.SetResult(null, "SugarCrystal");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "SpeedBand");
            recipe.AddIngredient(null, "SugarCrystal");
            recipe.SetResult(null, "SugarBand");
            recipe.AddTile(TileID.TinkerersWorkbench);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CookieCrumbs", 3);
            recipe.AddIngredient(null, "SoftCookie", 6);
            recipe.AddIngredient(ItemID.Bone, 3);
            recipe.SetResult(null, "CookieRapier");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CookieCrumbs", 3);
            recipe.AddIngredient(null, "SugarDust", 18);
            recipe.AddIngredient(ItemID.Bone, 6);
            recipe.SetResult(null, "SugarSword");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CookieRapier");
            recipe.AddIngredient(null, "SugarSword");
            recipe.SetResult(null, "VanillaSwirl");
            recipe.AddTile(TileID.DemonAltar);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "VanillaSwirl");
            recipe.AddIngredient(ItemID.BrokenHeroSword);
            recipe.SetResult(null, "TrueVanillaSwirl");
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.ChlorophyteBar, 9);
            recipe.AddIngredient(null, "CookieCrumbs", 6);
            recipe.AddIngredient(null, "SoftCookie", 15);
            recipe.SetResult(null, "CookieClaymore");
            recipe.AddTile(null, "MilkTank");
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.BrokenHeroSword);
            recipe.AddIngredient(null, "CookieClaymore");
            recipe.SetResult(null, "TrueCookieClaymore");
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "TrueCookieClaymore");
            recipe.AddIngredient(null, "TrueVanillaSwirl");
            recipe.SetResult(null, "Sweetnir");
            recipe.AddTile(TileID.MythrilAnvil);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.Minishark);
            recipe.AddIngredient(null, "SoftCookie", 15);
            recipe.SetResult(null, "CookiePistol");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "CookiePistol");
            recipe.AddIngredient(null, "CookieDust", 20);
            recipe.AddIngredient(ItemID.SoulofMight);
            recipe.SetResult(null, "CookieBlaster");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "SugarTwig");
            recipe.AddIngredient(null, "CookieDust", 15);
            recipe.AddIngredient(ItemID.Diamond);
            recipe.SetResult(null, "SugarWand");
            recipe.AddTile(TileID.Sawmill);
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.MagicMissile);
            recipe.AddIngredient(ItemID.SharkFin);
            recipe.AddIngredient(null, "SugarDust", 5);
            recipe.AddIngredient(null, "SoftCookie", 10);
            recipe.SetResult(null, "DorpanRod");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.Ectoplasm, 6);
            recipe.AddIngredient(null, "SugarCube", 25);
            recipe.AddIngredient(null, "SoftCookie");
            recipe.AddIngredient(null, "CookieDust", 15);
            recipe.SetResult(null, "CookieRod");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(ItemID.SharkFin, 15);
            recipe.AddIngredient(null, "SugarCube", 25);
            recipe.AddIngredient(ItemID.Bone);
            recipe.SetResult(null, "SugarSharkLauncher");
            recipe.AddTile(null, "MilkTank");
            recipe.AddRecipe();
	    recipe = new ModRecipe(mod);
	    recipe.AddIngredient(ItemID.SharkFin, 5);
	    recipe.AddIngredient(null, "SugarDust", 15);
	    recipe.SetResult(null, "SugarSharkFin", 5);
	    recipe.AddTile(null, "MilkTank");
	    recipe.AddRecipe();
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "Popsicle");
            recipe.AddIngredient(null, "PinkPopsicle");
            recipe.AddIngredient(null, "PurplePopsicle");
            recipe.SetResult(null, "RainbowPopsicle", 3);
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "Popsicle");
            recipe.AddIngredient(null, "PinkPopsicle");
            recipe.AddIngredient(null, "RedPopsicle");
            recipe.SetResult(null, "RainbowPopsicle", 3);
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "GiantPopsicle");
            recipe.AddIngredient(null, "GiantPinkPopsicle");
            recipe.AddIngredient(null, "GiantPurplePopsicle");
            recipe.SetResult(null, "GiantRainbowPopsicle", 3);
            recipe = new ModRecipe(mod);
            recipe.AddIngredient(null, "GiantPopsicle");
            recipe.AddIngredient(null, "GiantPinkPopsicle");
            recipe.AddIngredient(null, "GiantRedPopsicle");
            recipe.SetResult(null, "GiantRainbowPopsicle", 3);
        }
    }
}